AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - 'Rakefile'
    - 'bin/**/*'
    - 'config.ru'
    - 'config/application.rb'
    - 'config/boot.rb'
    - 'config/environment.rb'
    - 'config/environments/**/*'
    - 'config/initializers/**/*'
    - 'config/puma.rb'
    - 'config/routes.rb'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'db/seeds.rb'
    - 'test/**/*'
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
