# frozen_string_literal: true

source 'https://rubygems.org'

ruby '~> 3.4'

gem 'jbuilder'
gem 'pg', '~> 1.5'
gem 'puma', '~> 6.5'
gem 'rack-cors'
gem 'rails', '~> 8.0'
gem 'redis', '~> 5.0'

group :development, :test do
  gem 'debug', platforms: %i[mri mswin mswin64 mingw x64_mingw]
  gem 'rubocop', require: false
end

group :development do
  gem 'web-console'
end

group :test do
  gem 'capybara'
  gem 'rspec-rails', '~> 7.0'
  gem 'selenium-webdriver'
end
