# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.4.9'

gem 'pg', '1.6.3'
gem 'puma', '6.6.1'
gem 'rack-cors', '3.0.0'
gem 'rails', '8.1.2'

group :development, :test do
  gem 'debug', '1.11.1', platforms: %i[mri mswin mswin64 mingw x64_mingw]
  gem 'rubocop', '1.85.1', require: false
end

group :test do
  gem 'rspec-rails', '7.1.1'
end
